# Derived from ./manifests
# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: registry
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: registry
  # namespace: registry
  labels:
    app: registry
    component: main
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: registry
        component: main
    spec:
      containers:
      - name: registry
        image: registry:2.5
        imagePullPolicy: Always
        resources:
          # keep request = limit to keep this container in guaranteed class
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: REGISTRY_HTTP_ADDR
          value: :5000
        - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
          value: /var/lib/registry
        volumeMounts:
        - name: image-store
          mountPath: /var/lib/registry
        ports:
        - containerPort: 5000
          name: registry
          protocol: TCP
      volumes:
      - name: image-store
        emptyDir: {}
        # persistentVolumeClaim:
        #   claimName: kube-registry-pvc
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: registry-proxy
  # namespace: registry
  labels:
    app: registry
    component: proxy
spec:
  template:
    metadata:
      labels:
        app: registry
        component: proxy
    spec:
      containers:
      - name: registry-proxy
        image: gcr.io/google_containers/kube-registry-proxy:0.3
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
        env:
        - name: REGISTRY_HOST
          value: docker-registry.default.svc
          # value: registry.registry.svc
        - name: REGISTRY_PORT
          value: "5000"
        - name: FORWARD_PORT
          value: "5000"
        ports:
        - name: registry
          containerPort: 5000
          hostPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: docker-registry
  # namespace: registry
  labels:
    app: registry
    component: main
spec:
  type: NodePort
  ports:
  - name: registry
    port: 5000
    protocol: TCP
  selector:
    app: registry
    component: main
