apiVersion: v1
kind: Pod
metadata:
  name: docker-test
spec:
  containers:
  - name: docker
    image: docker:dind
#    command: ["dockerd-entrypoint.sh"]
    args: ["--insecure-registry", "registry.registry.svc:5000"]
    tty: true
    volumeMounts:
    - name: dockersock
      mountPath: /var/run/docker.sock
  volumes:
  - name: dockersock
    hostPath:
      path: /var/run/docker.sock
